replicaCount: 1

appInClusterNamespace: default

targetCluster:
  labelSelector:
    matchLabels:
      #vendor: "ICP"
      #region: "US"
      environment: Dev
      #datacenter: "toronto"
      #owner: "marketing"
  resourceSelector:
    type: cpu
  compliances: ""

chartRepoURL: https://raw.githubusercontent.com/antonyp63/kubernetes-multicloud-management/master/demos/guestbook/chart-packages